export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_TYPES = 'GET_TYPES';
export const GET_NAME_POKEMON = 'GET_NAME_POKEMON';
export const FILTER_CREATED = 'FILTER_CREATED';
export const FILTER_BY_TYPES = 'FILTER_BY_TYPES';
export const FILTER_ABC = 'FILTER_ABC';